version: 2

multi-ecosystem-groups:
  tauri:
    schedule:
      interval: weekly
      day: monday
      time: '02:00'
      timezone: Etc/UTC

updates:
  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase
    multi-ecosystem-group: tauri
    patterns:
      - '@tauri-apps/*'

  - package-ecosystem: cargo
    directory: /src-tauri
    multi-ecosystem-group: tauri
    patterns:
      - tauri*

  - package-ecosystem: npm
    directory: /
    versioning-strategy: increase
    schedule:
      interval: weekly
      day: monday
      time: '02:30'
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: '@tauri-apps/*'
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
      day: monday
      time: '03:00'
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: tauri*
    groups:
      cargo-minor-and-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '03:30'
      timezone: Etc/UTC
